apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "heimdall.fullname" . }}-clusterrole
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "heimdall.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "heimdall.fullname" . }}-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  {{ include "heimdall.fullname" . }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ include "heimdall.fullname" . }}-sa
    namespace: {{ .Release.Namespace }}