apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "heimdall.fullname" . }}-proxy
spec:
  selector:
    matchLabels:
      cattle.io/app: {{ include "heimdall.fullname" . }}-proxy
  template:
    metadata:
      labels:
        cattle.io/app: {{ include "heimdall.fullname" . }}-proxy
    spec:
      containers:
        - name: proxy
          image: {{ .Values.proxy.image }}:{{ .Values.proxy.tag }}
          imagePullPolicy: {{ .Values.proxy.imagePullPolicy }}
          env:
          - name: HEIMDALL_SVC
            value: {{ include "heimdall.fullname" . }}
          - name: HEIMDALL_NAMESPACE
            value: {{ .Release.Namespace }}
          - name: HEIMDALL_PORT
            value: {{ .Values.heimdall.service.port | quote }}
          - name: PROXY_PORT
            value: {{ .Values.proxy.port | quote }}
          ports:
          - containerPort: {{ .Values.proxy.port }}
            protocol: TCP
            name: http
